# our base image
FROM python:3.7-alpine

# Install python and pip
RUN apk add --update python py3-pip
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install Python modules needed by the Python app
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt

# copy files required for the app to run
COPY main.py /usr/src/app/
COPY main-raw.py /usr/src/app/
COPY templates/chatSimple.html /usr/src/app/templates/chatSimple.html
COPY aiml /usr/src/app/aiml


# run the application
CMD ["python", "/usr/src/app/main.py"]
